# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GMailApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GMailApp
  pod 'GoogleAPIClientForREST/Gmail', '~> 1.2.1'
  pod 'Google/SignIn'
end
